  allow_failures:
    - rvm: ruby-head
      gemfile: 'gemfiles/Gemfile.ruby-head'
  include:
    - rvm: 2.4.7
    - rvm: 2.5.6
    - rvm: 2.6.4
    - rvm: ruby-head
      gemfile: 'gemfiles/Gemfile.ruby-head'

    - language: generic
      env:
        - JRUBY_OPTS="--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -Xcompile.invokedynamic=false -J-Xmx1536m"
        - JRUBY_VERSION="jruby-9.2.9.0"
      before_install:
        - ./ci/build/rvm_setup.sh
        - rm -f ${HOME}/.rvm/gemsets/jruby/global.gems
        - rvm use ${JRUBY_VERSION} --install --binary --fuzzy
        - gem install bundler -v 1.17.3
      install: bundle install --binstubs --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
      script: bundle exec rake

bundler_args: "--binstubs --jobs=3 --retry=3"

cache: bundler

notifications:
  slack:
    secure: zRaFU5A0xPyaxafC4OeGIin/3WPMaFnhSF+NdN2+rpDg1pGo4j/Gdpw2lBljY5W7pK3DzzvNdJlK8F3LkDnFj0F3ox595Pq6cr0kYQP5u7WAv9cBm/Em1Q64++zn04Z2bRFwiTmz61uFQB2SFEuj3ti1BGcDSFXQwzqNZ0V1M4VGn19WEB2rUttvb286jSRHFsGaEUzMP7hXVzdP1iK8rI9nwN5h7uFoT5oz2yeYPExYu/d4j6Jp0gS3LJdtqkGdr1JNQbI4MDvm8mrAXfwG48QUS4ibFm3vOb4iZGRPJn42jDYFdegJfUMFU+Voexsf8epORg0UecLqKFst0c+A6PHY7oz24sSG+e5ZOZdIVudKUoW33t4dudiLq9YbdEgkBm6l8vC07HoJL6sfmCE2n1E+SkwTxa8tCxxWdXh05EIStkncmVNob92B8/9PUvfZRqInlCRQClNVrx+6Ehp6XQE6XWwR2WLJZCM+tWaRh/etfK5lnp4yX98zwzoMx5O1lmmTm6JYJ/9ZyRj6lhiDSL+P09EcnkQLGQ5o6c+uIwqg5cMpW/6VM3DNNsR98lekt+Ah/s6x7dc0k3YwFrU+yxmEyPgEqqMCWh7Ba7BjgDgU3d63iLiffbNJ7Ea1wl5VLTLsjR78AoF0WiAP/eyRdJvBe9sdS14YIV2Ua3sBosA=
sudo: false
dist: trusty
before_install:
  # Rubygems > 3.0.0 no longer supported rubies < 2.3
  - gem install "rubygems-update:<3.0.0" --no-document && update_rubygems
  # Bundler 2.0 is not supported by Rails < 5
  - gem list -i bundler -v '>= 2.0.0' && rvm @global do gem uninstall bundler -x || true
  - gem install bundler -v '~> 1.17'
before_script:
  - "bundle exec rake prepare_test_env"
script: "bundle exec rspec"
language: ruby
cache: bundler
services: mongodb
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - ruby-head
  #  TODO: investigate failure
  #  This is an arbitrary failure on travis
  #- jruby-19mode
  #- jruby-head
  #- rbx-19mode
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile
  - gemfiles/mongoid5.gemfile
  - gemfiles/mongoid6.gemfile
  - gemfiles/mongoid7.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails6.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/mongoid5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/mongoid6.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/mongoid7.gemfile

    - rvm: 2.0.0
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/mongoid5.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/mongoid6.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/mongoid7.gemfile

    - rvm: 2.1.10
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/mongoid5.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/mongoid6.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/mongoid7.gemfile

    - rvm: 2.2.10
      gemfile: gemfiles/rails6.gemfile

    - rvm: 2.3.8
      gemfile: gemfiles/rails6.gemfile

    - rvm: 2.4.9
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/mongoid2.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/mongoid3.gemfile

    - rvm: 2.5.7
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/mongoid2.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/mongoid3.gemfile

    - rvm: 2.6.5
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/mongoid2.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/mongoid3.gemfile

    - rvm: ruby-head
      gemfile: gemfiles/rails3.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails4.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/mongoid2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/mongoid3.gemfile

notifications:
  recipients:
    - andreas@aloop.org
